In [5]:
from qpricesim.simulations.mc_simulation_job_array import run_specific_specification
import numpy as np

In [27]:
params = {
  "n_agent": 3,
  "k_memory": 1,
  "discount_rate": 7/10,
  "exploration_rate": 1,
  "min_price": 600,
  "max_price": 1000,
  "reservation_price": 1000,
  "m_consumer": 24,
  "step": 400,
  "learning_iterations": 1000000000,
  "rounds_convergence": 100000,
  "Q_star_threshold": 1e-09,
  "avg_price_rounds": 1000
}

In [28]:
results = run_specific_specification(beta=1e-7, alpha=0.02, base_parameter=params, random_seed=1)

We converged for the agent with beta=1e-07 and alpha=0.02
Last state for agent with beta=1e-07 and alpha=0.02 = 5
It took us t=100158 training iterations to converge
Did we converge? True


In [29]:
print(run_specific_specification.__doc__)


    Runs a specific simulation for a fixed beta, alpha and random_seed.

    Args:
        beta (float): Decay parameter for the exploration rate
        alpha (float): Learning rate
        base_parameter (dict): Parameter dictionary as described somewhere else TODO
        random_seed (list): Random seed to be used

    Returns:
        list: Outcomes: profitability_state, weighted_profitability, best_response_share,
              avg_profit, state, trained_agents

              profitability_state (float): Value of the state of convergence
              weighted_profitability (float): Average profitability across all states
                                              weighted by the best_response_share
              best_response_share (float): Share of states in which the agent plays
                                           the best reponse (Optimality criterion).
              avg_profit (float): Average of the value of all states.
              prices_upon_convergence (float

In [30]:
results

(array([28005.31613173, 27920.30463313, 27756.88813739]),
 array([27886.65506448, 27658.02693527, 27857.28384119]),
 array([1., 1., 1.]),
 array([27886.65506448, 27658.02693527, 27857.28384119]),
 array([[600, 600, 600],
        [600, 600, 600],
        [600, 600, 600],
        ...,
        [600, 600, 600],
        [600, 600, 600],
        [600, 600, 600]], dtype=int64),
 array([1., 1., 1.]),
 5,
  <qpricesim.model_code.QLearningAgent.QLearningAgentBase at 0x241ab09fa48>])